/* REINICIAR DATABASE */
DROP DATABASE IF EXISTS uc11;
/* CRIAR DATABASE */
CREATE DATABASE IF NOT EXISTS uc11;
/* USAR DATABASE */
USE uc11;

CREATE TABLE produtos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    valor INT NOT NULL,
    status VARCHAR(20)
);

SELECT * FROM produtos;